name: Shellcheck

on:
  push:
    branches: ["Production"]
  pull_request:
    branches: ["Production"]

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@Production
        env:
          SHELLCHECK_OPTS: -e SC1091
